### ISSUE TITLE
Make coastline field names consistent

### ISSUE THREAD

**Issue by kamicut** [moradology/osmesa-stat-server#9]
Some coastline metrics are plural, and some are singular 
- https://github.com/azavea/osmesa-stat-server/search?q=coastline&unscoped_q=coastline
- https://github.com/azavea/osmesa-stat-server/search?q=coastline&unscoped_q=coastlines

Can we make all the metrics plural for consistency?

**Comment by sethfitz** [comment]
Perhaps. The reason that it's this way is that we're talking about kilometers of coastline (where "coastline" is the [singular] type of feature) mapped and coastline features added/modified (plural).

The same is true of roads and waterways.

**Comment by jpolchlo** [comment]
Indeed, consistency with these other categories was our principle concern.  Though, I think we could fairly easily adjust the output of the stat server without particularly upsetting the apple cart.

**Comment by jpolchlo** [comment]
Was this handled by #10, @kamicut?

**Comment by kamicut** [comment]
Yes, I'll close
